### ISSUE TITLE
Support more xml data in xmls, add theses infos in api

### ISSUE THREAD

**Issue by metheore** [HFScode/zspin#32]
Nécessité de tirer des données du xml un rendu sur les thèmes.

**Old xml:**
  
  
`  <game name="dino" index="True" image="">

        <game name="dino" index="True" image="">
    	<description>Cadillacs and Dinosaurs</description>  
		<cloneof>...</cloneof>  
		<crc>75CAC250</crc>  
		<manufacturer>Capcom</manufacturer>  
		<year>1993</year>  
		<genre>Beat them all</genre>  
		<rating>ESRB - E</rating>  
		<enabled>yes</enabled>  
</game>  `

**new xml:**

`  <game name="Mortal Kombat (Europe) (Rev 1)" index="True" image="">

        <game name="Mortal Kombat (Europe) (Rev 1)" index="True" image="">
		<description>Mortal Kombat</description>
		<cloneof>...</cloneof>
		<crc>...</crc>
		<systems>SNES, GB, GEN, SMS, PC, GG, SCD, ARC, AMI</systems>
		<manufacturer>Acclaim</manufacturer>
		<developer>Sculptured Software</developer>
		<year>1993</year>
		<genre>Combat</genre>
		<rating>SELL - NR</rating>
		<score>13</score>
		<players>1 joueur</players>
		<language>UK</language>
		<synopsis>Battez vos adversaires pour défier le guerrier Shokan nommé Goro, champion du tournoi depuis plus de 500 ans. Adaptation du célébrissime jeu d'arcade, Super NES sur Game Gear vous permet d'incarner 8 prétendants à la victoire finale, dont les protégés du seigneur Raiden, seuls remparts contre la menace qui pèse sur le Royaume de la Terre.</synopsis>
		<enabled>yes</enabled>
</game>`

Dans un premier temps il faut si aucun artwork est disponible afficher l'information quand elle est demandée en texte comme sous hyperspin.

![sans titre](https://cloud.githubusercontent.com/assets/8459415/9881935/7f529c90-5bd2-11e5-8063-0d4573c83721.png)

Mais surtout offrir la possibilité d'appeler des artworks génériques classés comme suit:

Media
.Global
..Systems
..Manufacturer
..Developer
..Year
..Genre
..Rating
..Score
..Players
..Language
..Synopsis

Le thème appellerait par exemple l'information *manufacturer*  et dans notre exemple afficherait si il est disponible le Acclaim.png.

Nous pourrions ainsi obtenir ce genre de résultat.

![402740grandlogohfs](https://cloud.githubusercontent.com/assets/8459415/9882111/6be87d4a-5bd3-11e5-8595-805f34f890e8.png)

**Comment by Inquisitom** [comment]
Afin de pouvoir gérer plusieurs genres pour une entrée, je proposerai ceci : 
<genre>
    <item>Beat them all</item>
    <item>Fighting</item>
    <item>etc...</item>
</genre>

**Comment by Inquisitom** [comment]
L'extension des infos sur les XMLs devrait être également implémentée pour les systèmes ("Main Menu.xml").
Il faudrait définir les tags : 
- year_release_US
- year_release_EU
- year_release_JP
- description
- type (console, ordi etc ...)

A creuser

**Comment by metheore** [comment]
Apres test sur le main menu.xml de la HFSBox, un ajout du genre: 

<menu>
  <game name="Capcom Play System">
  <genre>Arcade</genre>
  </game>
  <game name="Capcom Play System 2"/>
  <game name="Capcom Play System 3"/>
  <game name="IGS Polygame Master"/>
</menu>

n’interfère pas dans l'utilisation d'hyperspin.

**Comment by vikbez** [comment]
:+1:

**Comment by vikbez** [comment]
implemented
