### ISSUE TITLE
No video on linux build

### ISSUE THREAD

**Issue by Pnumekin** [HFScode/zspin#38]
Videos doesn't play (theme and intro), even with "libflashplayer.so" copied to zspin/libraries/linux64/flashplayer before compiling.

**Comment by vikbez** [comment]
check on release https://github.com/HFScode/zspin/releases/tag/v0.2.1

**Comment by Pnumekin** [comment]
Just compiled and tested 0.2.1, it works !
All video are ok, thank you very much.

**Comment by vikbez** [comment]
for 0.2.1 you have the linux release ready to download :)
