### ISSUE TITLE
Gestion du verouillage de la hauteur des Videos

### ISSUE THREAD

**Issue by camarade35** [HFScode/zspin#41]
Quand je crée une div comme ceci :
    #video {
      position: relative;
      top: 13.25%;
      right: 24%;
      width: 100%;
      height: 42%;
    }
    .gwd-video-17q3 {
      position: absolute;
      height: 100%;
      right: 0%;
      border-style: solid;
    }

Seule la gestion de la largeur est prise en charge et c'est elle qui gère la hauteur.

**Comment by Inquisitom** [comment]
Essaye ça : 
http://www.quirksmode.org/css/units-values/viewport.html

Je pense que ça pourrait faire ton affaire ... à tester.

**Comment by camarade35** [comment]
Merci Tom ;)

**Comment by Inquisitom** [comment]
Donc Bug à clôturer ?

**Comment by camarade35** [comment]
oui, voici la solution pour mon problème et donc sans div

.gwd-video-17q3 {
      position: absolute;
      width: 26%;
      max-height: 40vh;
      left: 2.75%;
      top: 17.6%;
      opacity: 0;
    }
