### ISSUE TITLE
Reflect wheel.json

### ISSUE THREAD

**Issue by camarade35** [HFScode/zspin#62]
Add in wheel.json an option to show a reflection under the wheels with if possible the choice of the height of the reflection.

Like this : 

![pc_engine](https://cloud.githubusercontent.com/assets/8459389/18747449/c137d26c-80cd-11e6-94a7-18fa5fb8610b.png)

**Comment by vikbez** [comment]
Please read the documentation of what arguments accept jswheel (that is another project: https://github.com/vikbez/jswheel) here: http://greensock.com/get-started-js#css
